# Generated by Django 4.0.2 on 2022-03-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_created_orderitem_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_delivered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Verified', 'Verified'), ('Processing', 'Processing'), ('Picking', 'Picking'), ('On the way', 'On the way'), ('Delivered', 'Delivered')], default='Placed', max_length=20),
        ),
    ]
