# Generated by Django 4.0.2 on 2022-03-31 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_delivery_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='khalti_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'COD'), ('Khalti', 'Khalti')], default='COD', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Verified', 'Verified'), ('On the way to restaurant', 'On the way to restaurant'), ('Processing', 'Processing'), ('Picking', 'Picking'), ('On the way', 'On the way'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Placed', max_length=100),
        ),
    ]
