# Generated by Django 4.0.2 on 2022-04-05 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_person', '0003_deliveryperson_location'),
        ('orders', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_orders', to='delivery_person.deliveryperson'),
        ),
        migrations.AddField(
            model_name='order',
            name='accepted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Verified', 'Verified'), ('On the way to restaurant', 'On the way to restaurant'), ('Processing', 'Processing'), ('Picking', 'Picking'), ('On the way', 'On the way'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Placed', max_length=100),
        ),
    ]
