# Generated by Django 4.0.2 on 2022-02-17 06:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='created',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='updated',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='is_veg',
            field=models.BooleanField(default=False),
        ),
    ]
