# Generated by Django 4.0.2 on 2022-02-19 11:41

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('foods', '0002_food_created_food_updated_alter_food_is_veg'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
