# Generated by Django 4.0.2 on 2022-02-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_foodtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
