# Generated by Django 4.0.2 on 2022-04-04 15:00

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_alter_food_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodtemplate',
            options={'ordering': ('-is_available', '-usage', 'name')},
        ),
        migrations.AddField(
            model_name='foodtemplate',
            name='usage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='foodtemplate',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
