# Generated by Django 4.0.2 on 2022-03-01 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_alter_food_image'),
        ('cart', '0002_alter_cart_options_remove_cart_user_cart_customer_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'food')},
        ),
    ]
