# Generated by Django 4.0.2 on 2022-02-28 09:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('comment', models.TextField(blank=True)),
                ('object_id', models.PositiveIntegerField()),
                ('sentiment_score', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('created', models.TimeField(auto_now_add=True)),
                ('updated', models.TimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='contenttypes.contenttype')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='customers.customer')),
            ],
        ),
    ]
