# Generated by Django 4.0.2 on 2022-05-05 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('reviews', '0003_remove_review_sentiment_score'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('customer', 'content_type', 'object_id')},
        ),
    ]
