# Generated by Django 4.0.2 on 2022-03-24 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('favourites', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together={('customer', 'content_type', 'object_id')},
        ),
    ]
