# Generated by Django 4.0.2 on 2022-04-02 10:51

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_person', '0002_registerdeliveryuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryperson',
            name='location',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500), default=list, size=2),
        ),
    ]
